### ISSUE TITLE
UML Diagramming Tool

### ISSUE THREAD

**Issue by ariefhasan** [BelajarJavaBareng/bpersonalia#10]
Selanjutnya apa UML Diagramming yg akan kita pake. Para member silakan comment, yg terbanyak jadi official Diagramming tool-nya. Saya pilih Visual Paradigm.

**Comment by azism** [comment]
saya starUML

**Comment by pnukeid** [comment]
boleh tuh visual paradigm.

**Comment by ndwijaya** [comment]
mungkin cukup dibuat usecase diagram dulu. tapi usecase baru dibuat setelah kita punya draft roadmapnya.
