### ISSUE TITLE
Software Stack

### ISSUE THREAD

**Issue by ariefhasan** [BelajarJavaBareng/bpersonalia#11]
Kita buat kesepakatan tuk software stacknya. Silakan pada comment pilihannya tuk software yg akan kita gunakan.
Pilihan saya:

Platform : Java EE (JPA, EJB)
UI : JSF dan pake lib Primefaces
DB: PostgreSQL
App Server: Glassfish 4
Reporting: JasperReports

**Comment by zakyalvan** [comment]
Saya sih biar sesuai kesepakatan awal dan ngikut team lain, spring for all stack, mybatis (baru belajar). karena cuma servlet base,saya lebih senang cuma dibatasi versi servletnya,misal 3.0, standarin servlet container atau app server tertentu terlalu kasar,hihihi. Testing pake junit+spring-test+mockito.db postgresql.ui ya tymeleaf atau jsp ndak masalah (+custom bootstrap di depan).

**Comment by ariefhasan** [comment]
seperti semua standar spesifikasi java punya reference implementation, maka menurut saya untuk project ini kita butuh reference container juga tuk development, fungsinya seperti alat ukur

**Comment by zakyalvan** [comment]
ok untuk tujuannya begitu,jadi redaksinya bukan harus pake produk ini untuk development,tapi harus jalan di produk ini sebagai standard.

**Comment by pnukeid** [comment]
btw maksudnya bagaimana sih, kok saya kurang mudeng... :)

**Comment by hgrea** [comment]
karna saya masih sangat baru, bahkan ini project pertama yang saya ikuti, jadi masih bingung, tapi kalo untuk app server mungkin saya lebih memilih tomcat, dikarenakan itu lebih ringan dibanding glassfish menurut saya.

**Comment by ndwijaya** [comment]
Maaf saya baru bisa monitor lagi. karena kebetulan saya sedang ada customer baru Go Live. biasa harus monitor segala kemungkinan dan dekat customer.

oya mengenai technology, dasar pertimbangan pemilihan sebaiknya bukan karen hal2 berikut :
1. saya bisanya itu. saya biasa pakai itu.
2. apalagi karena stack itu keren.

untuk opensource sebaiknya pertimbangannya adalah :
1. learning curve yang pendek, dengan pendeknya waktu mempelajari oleh member baru. maka akan semakin banyak yang bisa berkontribusi, dan ujung2nya opensource ini bisa tumbuh terus.
2. harus dipertimbangan juga group lain bpustaka memakai apa, karena nantinya kita kan berkolaborasi juga dengan mereka untuk membuat opensource yang lebih besar lagi yaitu e-comerse dan lain2nya.

saya pakai EJB tahun 2001-2003, dan pengalaman saya salah satu kekurangannya adalah learning curve yang cukup panjang buat developer baru, dan juga development lebih rumit yang ujungnya software akan jadi lebih lama.

saya pakai PriceFaces 2011-2012, ini technology simple diawal, tapi pada tahap2 advance banyak problem dan djlemit. makanya saya putuskan memakai spring-MVC dan myBatis. 

mohon yang legowo untuk sama2 belajar stack yang baru ini. percaya sama saya dulu sekal ini. ini tech tidak btuh waktu lama anda belajarnya. dan pertimbangkan bahwa kalau anda belum biasa pakai ini, anda akan jadi punya skill double. tahu yang baru. dan nanti bisa membandingkan dengan lebih bijaksana. 

saya sendiri paling familiar pakai GWT-Vaadin-Errai tapi saya tidak paksakan pakai itu karena kurang cocok dan developmentnya bisa lama kalau pakai GWT.

ini pendapat saya, tapi kalau suara mayoritas berbeda saya akan follow. buat saya ganti framework itu asik2 saja. tapi inget ini proyek intensi awalnya adalah untuk belajar. karena dari kalian nanti dipilih yang diundang untuk ikut proyek yang lebih serius.

kalau stacknya jauh beda, nanti dijamin belajar lagi dari awal. tapi jadi tahu banyak juga.

begitu saja dari saya.

**Comment by ariefhasan** [comment]
Tidak masalah apakah Java EE atau Spring, benar yg serius ikut project ini harus legowo, termasuk saya sendiri. Sepertinya Spring jadi pilihan terbanyak.

**Comment by hgrea** [comment]
kalo menurut saya lebih baik spring, karna tutorial dirasa juga sudah cukup banyak, dan untuk db menurut saya postgresql sudah sangat bagus, kemudian untuk UI saya saran angularjs atau html5, dan juga g perlu tampilan bagus-bagus di awal, yang penting bisa jalan dulu.
monggo di tunggu saran yang lain biar bisa dapat solusi terbaik.

**Comment by ndwijaya** [comment]
ok good. kalau sudah bisa disepakati. kita putuskan 
pakai spring MVC
persistance layer pakai mybatis.

bisa di closed issue ini ?

kita akan berangkat ke step berikutnya untuk kickstart springMVC dan kickstart mybatis.

**Comment by Code21k** [comment]
Oke,,
