### ISSUE TITLE
methodoly project 

### ISSUE THREAD

**Issue by ndwijaya** [BelajarJavaBareng/bpersonalia#12]
saya lihat issue yang diposting sudah bicara jauh seperti UML, class diagram dst. dan saya sepertinya membaca kita mau waterfall ?
gpp sih itu bagus. tapi sebaiknya kita jangan bikin proyek mindahin gunung. pasti susah dan peluang gagal akan besar. 

saran saya kita sebaiknya sedikit Agile, belajar memulai dari hal kecil namun dilakukan iterasi berkali2 sehingga menuju tujuan besar. 

silahkan pendapat yang lain monggo di rojer.

**Comment by ariefhasan** [comment]
Saya setuju Agile method, lebih cepat kelihatan progressnya

**Comment by goeroeku** [comment]
vote usulan om mentor Agile (y)

**Comment by ndwijaya** [comment]
ok. kalau kita putuskan dan issue ini di closed saja.
