### ISSUE TITLE
Usulan Pertemuan Finalisasi Perlengkapan Project

### ISSUE THREAD

**Issue by armintosan** [BelajarJavaBareng/bpersonalia#13]
selamat siang suadar - suadara

saya ijin untuk menyampaikan usulan.

untuk memutuskan secara final mengenai tool apa yang dipake dan metologi develepment pake sdlc/waterfall/agile kalau boleh saya usul dilakukan pertemuan saja.

hal ini menutut saya perlu karena :
1.tidak semua member sudah mengerti cara install tool yang digunakan, 
	dengan diadakan pertemuan diharapkan bila ada team kesulitan bisa dibantu dengan cepat.
	saya sendiri masih new bie tentang teknologi java karena back groud saya sendiri kerjanya ngurusin dokumen (BA).
2.untuk mengenal satu sama lain ,sehingga solidaritas team semakin kompak
3.perlu adanya penugasan dan tanggung jawab terhadat job desk masing masing
4.karena ini bersifat project tentunya harus ditentukan kapan start dan finisnya,Penyusan project charter ,saya kira lebih baik dilakukan dengan mengadakan pertemuan

terima kasih atas perhatianya

Arminto

0858-8833-7460

**Comment by ndwijaya** [comment]
Sdr. Arminto.

mempertimbangkan bahwa tidak mudah mempertemukan banyak orang yang lokasinya berbeda2 dan juga time/waktu yang mungkin kesibukannya masing2. mungkin kita tdk janji dulu bisa mempertemukan di phase2 awal.

terkait tools sudah diputuskan :
Editor bebas - Eclipse - NetBean - TextPad - notepad - ItelliJIdea semua bisa.
software stack :
  * spring MVC
  * mybatis
  * meaven
  * postgreSQL

appserver bebas yang penting support J2EE

saya close issue in ya ?

**Comment by sikurro** [comment]
yups.. close Om :+1:
