### ISSUE TITLE
Some Files Missing from My Latest Commit

### ISSUE THREAD

**Issue by zakyalvan** [BelajarJavaBareng/bpersonalia#17]
After pulling latest code from team's repo, I realize several files missing from my latest commit (for example file inside src/test/java). And I cant  trace when the files have gone. Sorry bro @ariefhasan , this happen after your commit today. Sorry yak, sorry yak, nge-rebase branch local gw jadi repot.

**Comment by ariefhasan** [comment]
Sory bro @zakyalvan tadi salah ngeklik rebase di netbeans, bisakah diperbaiki ?, biasanya pake bitbucket, pake github di netbeans masih sering gk bisa push commit dan muncul error aneh2

**Comment by zakyalvan** [comment]
Ok, ndak apaapa bro,note aja,biar samasama enak.gw benerin ya.
