### ISSUE TITLE
Tentang Indentasi Kode

### ISSUE THREAD

**Issue by zakyalvan** [BelajarJavaBareng/bpersonalia#18]
Mau tanya tentang konvensi kode khususnya masalah indentasi,apakah mau pake tab atau spasi?kalau spasi dua spasi atau empat spasi?biar si mbak gitty ga seringsering ngelapor konflik untuk masalah ini,misalnya garagara ngerapihin kode. Makasih!

**Comment by ariefhasan** [comment]
Gimana klo coding-nya pake referensi ini aja:
https://google-styleguide.googlecode.com/svn/trunk/javaguide.html

**Comment by Code21k** [comment]
ane setuju si pake google style tapi kalo menurut ane lebih baik modif sedikit untuk 

a {
}

jadi

a
{
}

**Comment by ariefhasan** [comment]
@Code21k  klo setuju harusnya jgn ada kata "tapi".....hahaha

**Comment by zakyalvan** [comment]
masalah indentasi?spasi atau tab?untuk contoh di atas, lebih cantik yang pertama, baris lebih dikit :tongue:

**Comment by ariefhasan** [comment]
@BelajarJavaBareng/developer-bpersonalia  masalah coding style diputuskan pake google style aja, setuju ?, klo setuju issue ini segera di close aja

**Comment by zakyalvan** [comment]
Ok ok,siap kumendan!
