### ISSUE TITLE
IDE (Integrated Development Environment)

### ISSUE THREAD

**Issue by ariefhasan** [BelajarJavaBareng/bpersonalia#9]
Kita samakan dulu IDE yg digunakan untuk coding, para member group ini silakan comment. IDE dgn suara terbanyak adalah yg jadi official IDE group ini. Saya sendiri pilih Netbeans.

**Comment by azism** [comment]
netbeans

**Comment by aginanjar** [comment]
vote for netbeans juga.

**Comment by zakyalvan** [comment]
no no,kan kalo pake maven ya ga perlu batasin ide apa yg boleh dipake.jadi ndak perlu dibatesin lah,selama dukung maven ide nya

**Comment by sikurro** [comment]
Netbeans :+1:

**Comment by armintosan** [comment]
Netbeans

**Comment by rendito** [comment]
I prefer using STS

**Comment by hgrea** [comment]
Netbeans saya rasa.

**Comment by hariali** [comment]
Netbeans

**Comment by pnukeid** [comment]
terbiasa netbeans, tapi eclipse juga boleh sembari belajar,

**Comment by goeroeku** [comment]
vote netbeans
*cuma gara2 add referensi maven di netbeans lebih mudah kayaknya, atau mungkin belum explore lebih jauh dengan eclipse

**Comment by zakyalvan** [comment]
kalau mau nyoba ide yg eclipse base,mending sts aja sekalian.tapi balik lagi,ide itu lebih ke masalah selera dan kebiasaan.

**Comment by ndwijaya** [comment]
IDE kita putuskan open saja sesuai masing2 sukanya apa.
netbeans ok go head, mau eclipse go head. saya pakai IntelliJIdea community.

saya closed ini ya.
